name: lectio_wrapper
description: A client wrapper for Lectio. Everything runs and is scraped without thirdparty. This means it is as secure as typical Lectio browsing.
version: 0.5.19
homepage: https://oscarspalk.com
repository: https://github.com/oscarspalk/lectio_wrapper

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  beautiful_soup_dart: ^0.3.0
  intl: ^0.17.0
  dio: ^5.2.1+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dotenv: 4.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
